### ISSUE TITLE
ok, ur time is over

### ISSUE THREAD

**Issue by SnapDragon7410** [keselekpermen69/UserButt#1]

**Comment by SnapDragon7410** [comment]
its time to take down this userbot, since its kang

**Comment by keselekpermen69** [comment]
do what u want XD

**Comment by tomyprs25** [comment]
Woiyakah

**Comment by rzlamrr** [comment]
@tomyprs25 Ramein ah

**Comment by GudMeong** [comment]
@SnapDragon7410 SERAH GW DONG ANJING

**Comment by tomyprs25** [comment]
@rzlamrr @KeselekPermen69 Open dung

**Comment by rzlamrr** [comment]
@GudMeong Sellow

**Comment by tomyprs25** [comment]
Jangan pada spam cok kasian

**Comment by rzlamrr** [comment]
@tomyprs25 U yang spam jir

**Comment by MoveAngel** [comment]
@tomyprs25 akwokaokwoakwa ok its time del repo

**Comment by rzlamrr** [comment]
@MoveAngel Buset gada akhlaq

**Comment by belluxp** [comment]
@rzlamrr p

**Comment by remtzx** [comment]
bisik kontol

**Comment by GudMeong** [comment]
@remtzx mana

**Comment by remtzx** [comment]
> @remtzx mana

mana apaan

**Comment by remtzx** [comment]
p

**Comment by remtzx** [comment]
mikum

**Comment by keselekpermen69** [comment]
@remtzx Locked
